<template>
  <div class="loadingio-spinner-spin-zb4gadi0ikp">
    <div class="ldio-quf6d5eh8bh">
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
      <div><div></div></div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Loader",
};
</script>
<style type="text/css">
@keyframes ldio-quf6d5eh8bh {
  0% {
    opacity: 1;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1.5, 1.5);
  }
  100% {
    opacity: 0;
    backface-visibility: hidden;
    transform: translateZ(0) scale(1, 1);
  }
}
.ldio-quf6d5eh8bh div > div {
  position: absolute;
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: #ff727d;
  animation: ldio-quf6d5eh8bh 1s linear infinite;
}
.ldio-quf6d5eh8bh div:nth-child(1) > div {
  left: 168px;
  top: 88px;
  animation-delay: -0.875s;
}
.ldio-quf6d5eh8bh > div:nth-child(1) {
  transform: rotate(0deg);
  transform-origin: 180px 100px;
}
.ldio-quf6d5eh8bh div:nth-child(2) > div {
  left: 145px;
  top: 145px;
  animation-delay: -0.75s;
}
.ldio-quf6d5eh8bh > div:nth-child(2) {
  transform: rotate(45deg);
  transform-origin: 157px 157px;
}
.ldio-quf6d5eh8bh div:nth-child(3) > div {
  left: 88px;
  top: 168px;
  animation-delay: -0.625s;
}
.ldio-quf6d5eh8bh > div:nth-child(3) {
  transform: rotate(90deg);
  transform-origin: 100px 180px;
}
.ldio-quf6d5eh8bh div:nth-child(4) > div {
  left: 31px;
  top: 145px;
  animation-delay: -0.5s;
}
.ldio-quf6d5eh8bh > div:nth-child(4) {
  transform: rotate(135deg);
  transform-origin: 43px 157px;
}
.ldio-quf6d5eh8bh div:nth-child(5) > div {
  left: 8px;
  top: 88px;
  animation-delay: -0.375s;
}
.ldio-quf6d5eh8bh > div:nth-child(5) {
  transform: rotate(180deg);
  transform-origin: 20px 100px;
}
.ldio-quf6d5eh8bh div:nth-child(6) > div {
  left: 31px;
  top: 31px;
  animation-delay: -0.25s;
}
.ldio-quf6d5eh8bh > div:nth-child(6) {
  transform: rotate(225deg);
  transform-origin: 43px 43px;
}
.ldio-quf6d5eh8bh div:nth-child(7) > div {
  left: 88px;
  top: 8px;
  animation-delay: -0.125s;
}
.ldio-quf6d5eh8bh > div:nth-child(7) {
  transform: rotate(270deg);
  transform-origin: 100px 20px;
}
.ldio-quf6d5eh8bh div:nth-child(8) > div {
  left: 145px;
  top: 31px;
  animation-delay: 0s;
}
.ldio-quf6d5eh8bh > div:nth-child(8) {
  transform: rotate(315deg);
  transform-origin: 157px 43px;
}
.loadingio-spinner-spin-zb4gadi0ikp {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-quf6d5eh8bh {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-quf6d5eh8bh div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
